on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build Dependencies
        run: npm install
      - name: Build React App
        run: npm run build
      - name: Delete old static files
        run: aws s3 rm s3://www.whatalesyou.net --recursive
      - name: Deploy app build to S3 bucket
        run: aws s3 sync build s3://www.whatalesyou.net
