on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build Dependencies
        run: npm ci
      - name: Make .env for production
        if: github.ref == 'refs/heads/master'
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_APP_ENV: production
      - name: Make .env for staging
        if: github.ref == 'refs/heads/develop'
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_APP_ENV: staging
      - name: Build React App
        run: npm run build
      - name: Delete old static files production
        if: github.ref == 'refs/heads/master'
        run: aws s3 rm s3://www.whatalesyou.net --recursive
      - name: Delete old static files staging
        if: github.ref == 'refs/heads/develop'
        run: aws s3 rm s3://staging.whatalesyou.net --recursive
      - name: Deploy app build to S3 bucket production
        if: github.ref == 'refs/heads/master'
        run: aws s3 sync build s3://www.whatalesyou.net
      - name: Deploy app build to S3 bucket staging
        if: github.ref == 'refs/heads/develop'
        run: aws s3 sync build s3://staging.whatalesyou.net
      - name: Invalidate CloudFront cache
        if: github.ref == 'refs/heads/master'
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

